### ISSUE TITLE
emailverification check for global assurance

### ISSUE THREAD

**Issue by magwas** [edemo/PDOauth#103]
also: add global assurance forother assurances.

**Comment by Claymanus** [comment]
ie: email  address verification check needed to be able proceeding global assurance. 
- because of #106 , the workflow will be stopped until the email address verification, that means the user unable to use the sso service, so can't be assured.
- if the #115 will be accepted, an email trafic precedes processing assurance
- we can define the assurance process and restrictions global in #115 
Reopen if you don't agree
