### ISSUE TITLE
adding facebook credential fails 

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#118]
conditions:
- tryed login with SSL -> fail -> still on login page port 8080 (maybe would be nice redirecting to BASE URL #117 ? )
- logged in with password
- add facebook credential fails. no error message on UI.

**Comment by magwas** [comment]
"facebook fiók hozzárendelése" fails after SSL login.
May or may not the same bug. It should be something related to the redirect to 8080 due to SSL login, as it works with password login.
Error message:
ReferenceError: FB is not defined@ 2 ms
Source: 	
https://sso.edemokraciagep.org:8080/static/fb.js:67

**Comment by magwas** [comment]
please check it.
