### ISSUE TITLE
why ssl login redirects to :8080

### ISSUE THREAD

**Issue by Claymanus** [edemo/PDOauth#79]

**Comment by magwas** [comment]
Because SSL negotiation is done by the web server, and the easiest way for server administrator is to redirect to another port/site. See how cacert.org handles certificate login as an example.
Actually the redirect is to SSL_LOGIN_BASE_URL, so if one chooses to use different URIs within the same site (and configure ssl negotiation properly), then it is possible to have that.

**Comment by Claymanus** [comment]
Ezt beszéljük már át egy kicsit...
